boy_name = input("boy name>>")
boy_age = int(input(" boy age "))
girl_name = input("girl name>>")
girl_age = int(input(" girl age "))
age_diff = (boy_age - girl_age)
print(f"{boy_name} loves {girl_name}. age diffrence is {age_diff}")